baseURL: 'https://thqio.com'
languageCode: en-us
title: "THQio"
theme: PaperMod
paginate: 50


menu:
  main:
  - identifier: home
    name: Home Page
    url: /
    weight: 10
  - identifier: blog
    name: Blog
    url: /blog
    weight: 20
  - identifier: projects
    name: Projects
    url: /projects
    weight: 30
  - identifier: experience
    name: Experience
    url: /experience
    weight: 40
  - identifier: Internships
    name: Internships
    url: /internships
    weight: 45
  - identifier: search
    name: Search
    url: /search
    weight: 50
  - identifier: tags
    name: Tags
    url: /tags
    weight: 60

params:
  # theme
  showToc: true
  TocOpen: false
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  hideMeta: false
  editPost:
    URL: "mailto:tasneemhasanat97@icloud.com?subject=Suggestion"
    Text: "Suggest changes" # edit text
    appendFilePath: true # append file path to edit link

  # for enchanced SEO
  env: production

  # Home Page
  profileMode:
    enabled: true
    title: "Tasneem Hasanat"
    subtitle: |+
              **Full Stack Developer**

              **Composer**

              **Chef**
    imageUrl: "home/image.jpeg"
    imageTitle: "Magician"
    imageWidth: 250
    imageHeight: 250
    #buttons:
    #  - name: Resume
    #   url: "https://docs.google.com/document/d/1p-i8fW43f-D1ghAH1L6AOVhWvpNfDz8w/edit"

  # List View
  hideDescriptionInList: false

  # cover image for posts
  cover:
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

  socialIcons:
    - name: "email"
      url: "mailto:tasneemhasanat97@icloud.com"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/tasneemhasanat97"
    - name: "github"
      url: "https://github.com/tasneemhasanat97"
    - name: "youtube"
      url: "https://www.youtube.com/channel/UCWfuGJdMaEkL3SHwyAAvweA"
    - name: "cv"
      url: "https://docs.google.com/document/d/1Gjh1rEVGpRT1bqssKGq_Iu54Ibbk2B7nI_v_5bsMums/edit?usp=sharing"

  # text search
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

# for search using Fuse.js
outputs:
  home:
    - HTML
    - RSS
    - JSON

# allow HTML in MD
markup:
  goldmark:
    renderer:
      unsafe: true